# Generated by Django 6.0.3 on 2026-04-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_age_student_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, help_text='Date the student was admitted to the school', null=True),
        ),
    ]
