# Generated by Django 6.0.3 on 2026-04-06 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timetable_core_timeta_day_ded5d1_idx_and_more'),
        ('students', '0004_student_students_st_student_e7126a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_date'], name='students_st_enrollm_8263f3_idx'),
        ),
    ]
