# Generated by Django 6.0.3 on 2026-04-09 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_house'),
        ('students', '0005_student_students_st_enrollm_8263f3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.house'),
        ),
    ]
