# Generated by Django 6.0.3 on 2026-04-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='financial_block_override',
            field=models.BooleanField(default=False, help_text='If True, the student will have access even with unpaid fees.'),
        ),
    ]
