# Generated by Django 6.0.3 on 2026-04-06 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='core_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
