# Generated by Django 6.0.3 on 2026-04-06 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notification_recipients'),
        ('students', '0003_alter_student_enrollment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='core_assign_due_dat_5b7b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['class_assigned'], name='core_assign_class_a_c606a1_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['teacher'], name='core_assign_teacher_714ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='core_attend_date_801bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='core_attend_status_8c6988_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='core_attend_student_931c39_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['grade'], name='core_class_grade_a7dc69_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'subject'], name='core_result_student_a12fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['date'], name='core_result_date_5287ab_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['exam_type'], name='core_result_exam_ty_ad58a6_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'student'], name='core_submis_assignm_ac9603_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='core_submis_submitt_cc7493_idx'),
        ),
    ]
