# Generated by Django 6.0.3 on 2026-04-06 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment_core_assign_due_dat_5b7b5a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['day', 'start_time'], name='core_timeta_day_ded5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['teacher', 'day'], name='core_timeta_teacher_5afb6c_idx'),
        ),
    ]
