# Generated by Django 6.0.3 on 2026-04-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_submission_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='EduMS Intelligence', max_length=200)),
                ('motto', models.CharField(blank=True, default='Empowering Future Leaders', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('current_academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('established_year', models.IntegerField(default=2024)),
            ],
            options={
                'verbose_name': 'Institutional Configuration',
                'verbose_name_plural': 'Institutional Configuration',
            },
        ),
    ]
