# Generated by Django 6.0.3 on 2026-04-07 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_noticeboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('session', models.CharField(help_text='e.g. 2024/2025', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='name',
            field=models.CharField(default='Edu Ms Intelligence', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='active_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicterm'),
        ),
    ]
