# Generated by Django 6.0.3 on 2026-04-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_academicterm_alter_schoolconfiguration_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color_code', models.CharField(default='#4361ee', help_text='Hex color code for identification (e.g. #FF0000)', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Institutional House',
                'verbose_name_plural': 'Institutional Houses',
            },
        ),
    ]
