# Generated by Django 6.0.3 on 2026-04-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='currency_code',
            field=models.CharField(default='GHS', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='currency_symbol',
            field=models.CharField(default='GH₵', max_length=10),
        ),
    ]
