# Generated by Django 6.0.3 on 2026-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_schoolconfiguration_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='vacation_duration',
            field=models.CharField(default='3 Weeks', help_text="e.g. '3 Weeks', '1 Month'", max_length=100),
        ),
    ]
