# Generated by Django 6.0.3 on 2026-04-16 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_academicterm_vacation_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='motto',
            field=models.CharField(blank=True, help_text="The house's guiding philosophy.", max_length=200),
        ),
        migrations.AddField(
            model_name='house',
            name='patron',
            field=models.CharField(blank=True, help_text='The staff member or patron overseeing the house.', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='points',
            field=models.IntegerField(default=0, help_text='Cumulative point tally for the house.'),
        ),
        migrations.AlterField(
            model_name='house',
            name='color_code',
            field=models.CharField(default='#4361ee', help_text='Hex color code (e.g. Red=#FF0000)', max_length=20),
        ),
        migrations.CreateModel(
            name='HousePointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Positive for awards, negative for deductions.')),
                ('category', models.CharField(choices=[('academic', 'Academic Excellence'), ('sports', 'Sports & Athletics'), ('discipline', 'Disciplinary Action'), ('event', 'Institutional Event'), ('other', 'Other')], default='academic', max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to='core.house')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
