# Generated by Django 6.0.3 on 2026-04-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('grade', 'Grade'), ('attendance', 'Attendance'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('resource', 'Resource Material')], max_length=20),
        ),
    ]
