# Generated by Django 6.0.3 on 2026-04-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=30, verbose_name='Relationship to Teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('degree', "Bachelor's Degree"), ('masters', 'Masters Degree'), ('phd', 'PhD'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, help_text='Teaching specialization or area of expertise', max_length=100),
        ),
    ]
