# Generated by Django 6.0.3 on 2026-04-06 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment_core_assign_due_dat_5b7b5a_idx_and_more'),
        ('teachers', '0002_teacher_emergency_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher_id'], name='teachers_te_teacher_5d8d41_idx'),
        ),
    ]
