# Generated by Django 6.0.3 on 2026-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_teachers_te_teacher_5d8d41_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, help_text='Department (e.g. Science, Mathematics, Humanities)', max_length=100),
        ),
    ]
